set PATH=C:\D\dmd2\windows\bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\\Common7\IDE;C:\Program Files (x86)\Windows Kits\8.1\\bin;%PATH%

echo System\Collections\Generic\Comparer_T.d >Debug\DCorlib.build.rsp
echo System\Collections\Generic\Comparer_T_DefaultComparerT.d >>Debug\DCorlib.build.rsp
echo System\Collections\Generic\DefaultComparer_T.d >>Debug\DCorlib.build.rsp
echo System\Collections\Generic\Dictionary_TKey_TValue.d >>Debug\DCorlib.build.rsp
echo System\Collections\Generic\Dictionary_TKey_TValue_EnumeratorTKey_TValue.d >>Debug\DCorlib.build.rsp
echo System\Collections\Generic\Dictionary_TKey_TValue_KeyCollectionTKey_TValue.d >>Debug\DCorlib.build.rsp
echo System\Collections\Generic\Dictionary_TKey_TValue_KeyCollection_EnumeratorTKey_TValue.d >>Debug\DCorlib.build.rsp
echo System\Collections\Generic\Dictionary_TKey_TValue_ShimEnumeratorTKey_TValue.d >>Debug\DCorlib.build.rsp
echo System\Collections\Generic\Dictionary_TKey_TValue_Transform_TRetTKey_TValue.d >>Debug\DCorlib.build.rsp
echo System\Collections\Generic\Dictionary_TKey_TValue_ValueCollectionTKey_TValue.d >>Debug\DCorlib.build.rsp
echo System\Collections\Generic\Dictionary_TKey_TValue_ValueCollection_EnumeratorTKey_TValue.d >>Debug\DCorlib.build.rsp
echo System\Collections\Generic\EnumIntEqualityComparer_T.d >>Debug\DCorlib.build.rsp
echo System\Collections\Generic\EqualityComparer__G.d >>Debug\DCorlib.build.rsp
echo System\Collections\Generic\GenericComparer_T.d >>Debug\DCorlib.build.rsp
echo System\Collections\Generic\GenericEqualityComparer_T.d >>Debug\DCorlib.build.rsp
echo System\Collections\Generic\ICollection__G.d >>Debug\DCorlib.build.rsp
echo System\Collections\Generic\IComparer__G.d >>Debug\DCorlib.build.rsp
echo System\Collections\Generic\IDictionary_TKey_TValue.d >>Debug\DCorlib.build.rsp
echo System\Collections\Generic\IEnumerable__G.d >>Debug\DCorlib.build.rsp
echo System\Collections\Generic\IEnumerator__G.d >>Debug\DCorlib.build.rsp
echo System\Collections\Generic\IEqualityComparer__G.d >>Debug\DCorlib.build.rsp
echo System\Collections\Generic\IList__G.d >>Debug\DCorlib.build.rsp
echo System\Collections\Generic\IntEqualityComparer.d >>Debug\DCorlib.build.rsp
echo System\Collections\Generic\InternalStringComparer.d >>Debug\DCorlib.build.rsp
echo System\Collections\Generic\KeyNotFoundException.d >>Debug\DCorlib.build.rsp
echo System\Collections\Generic\KeyValuePair__G.d >>Debug\DCorlib.build.rsp
echo System\Collections\Generic\Link.d >>Debug\DCorlib.build.rsp
echo System\Collections\Generic\List_T_EnumeratorT.d >>Debug\DCorlib.build.rsp
echo System\Collections\Generic\List__G.d >>Debug\DCorlib.build.rsp
echo System\Collections\Generic\System.Collections.Generic.Namespace.d >>Debug\DCorlib.build.rsp
echo System\Collections\Collection.d >>Debug\DCorlib.build.rsp
echo System\Collections\Collections.d >>Debug\DCorlib.build.rsp
echo System\Collections\Hashtable.d >>Debug\DCorlib.build.rsp
echo System\Collections\Hashtable_Entry.d >>Debug\DCorlib.build.rsp
echo System\Collections\Hashtable_EnumeratorType.d >>Debug\DCorlib.build.rsp
echo System\Collections\Hashtable_HashtableEnumerator.d >>Debug\DCorlib.build.rsp
echo System\Collections\Hashtable_KeyCollection.d >>Debug\DCorlib.build.rsp
echo System\Collections\Hashtable_ValueCollection.d >>Debug\DCorlib.build.rsp
echo System\Collections\ICollection.d >>Debug\DCorlib.build.rsp
echo System\Collections\IDictionary.d >>Debug\DCorlib.build.rsp
echo System\Collections\IEnumerable.d >>Debug\DCorlib.build.rsp
echo System\Collections\IEnumerator.d >>Debug\DCorlib.build.rsp
echo System\Collections\IEqualityComparer.d >>Debug\DCorlib.build.rsp
echo System\Collections\IList.d >>Debug\DCorlib.build.rsp
echo System\Collections\SortedList.d >>Debug\DCorlib.build.rsp
echo System\Globalization\Namespace.d >>Debug\DCorlib.build.rsp
echo System\IO\File.d >>Debug\DCorlib.build.rsp
echo System\IO\System.IO.Namespace.d >>Debug\DCorlib.build.rsp
echo System\Reflection\Internal.d >>Debug\DCorlib.build.rsp
echo System\Reflection\Namespace.d >>Debug\DCorlib.build.rsp
echo System\Runtime\CompilerServices\Namespace.d >>Debug\DCorlib.build.rsp
echo System\Runtime\InteropServices\Namespace.d >>Debug\DCorlib.build.rsp
echo Namespace.d >>Debug\DCorlib.build.rsp
echo System\Text\Namespace.d >>Debug\DCorlib.build.rsp
echo System\Text\StringBuilder.d >>Debug\DCorlib.build.rsp
echo System\Threading\Namespace.d >>Debug\DCorlib.build.rsp
echo System\__Internal\Namespace.d >>Debug\DCorlib.build.rsp
echo System\__Internal\xxhash.d >>Debug\DCorlib.build.rsp
echo System\Action.d >>Debug\DCorlib.build.rsp
echo System\Action__G.d >>Debug\DCorlib.build.rsp
echo System\Activator.d >>Debug\DCorlib.build.rsp
echo System\ArgumentException.d >>Debug\DCorlib.build.rsp
echo System\Array.d >>Debug\DCorlib.build.rsp
echo System\Array_T.d >>Debug\DCorlib.build.rsp
echo System\Attribute.d >>Debug\DCorlib.build.rsp
echo System\Boolean.d >>Debug\DCorlib.build.rsp
echo System\Byte.d >>Debug\DCorlib.build.rsp
echo System\Char.d >>Debug\DCorlib.build.rsp
echo System\Comparison__G.d >>Debug\DCorlib.build.rsp
echo System\Console.d >>Debug\DCorlib.build.rsp
echo System\DateTime.d >>Debug\DCorlib.build.rsp
echo System\DateTimeKind.d >>Debug\DCorlib.build.rsp
echo System\DateTimeParse.d >>Debug\DCorlib.build.rsp
echo System\DayOfWeek.d >>Debug\DCorlib.build.rsp
echo System\Decimal.d >>Debug\DCorlib.build.rsp
echo System\Delegate.d >>Debug\DCorlib.build.rsp
echo System\Double.d >>Debug\DCorlib.build.rsp
echo System\EmptyArray_T.d >>Debug\DCorlib.build.rsp
echo System\Enum.d >>Debug\DCorlib.build.rsp
echo System\Environment.d >>Debug\DCorlib.build.rsp
echo System\EventArgs.d >>Debug\DCorlib.build.rsp
echo System\EventHandler.d >>Debug\DCorlib.build.rsp
echo System\EventHandler__G.d >>Debug\DCorlib.build.rsp
echo System\Func__G.d >>Debug\DCorlib.build.rsp
echo System\GC.d >>Debug\DCorlib.build.rsp
echo System\ICloneable.d >>Debug\DCorlib.build.rsp
echo System\IComparable.d >>Debug\DCorlib.build.rsp
echo System\IComparable__G.d >>Debug\DCorlib.build.rsp
echo System\IConvertible.d >>Debug\DCorlib.build.rsp
echo System\IDisposable.d >>Debug\DCorlib.build.rsp
echo System\IFormatProvider.d >>Debug\DCorlib.build.rsp
echo System\IFormattable.d >>Debug\DCorlib.build.rsp
echo System\Int16.d >>Debug\DCorlib.build.rsp
echo System\Int32.d >>Debug\DCorlib.build.rsp
echo System\Int64.d >>Debug\DCorlib.build.rsp
echo System\IntPtr.d >>Debug\DCorlib.build.rsp
echo System\Locale.d >>Debug\DCorlib.build.rsp
echo System\Math.d >>Debug\DCorlib.build.rsp
echo System\MulticastDelegate.d >>Debug\DCorlib.build.rsp
echo System\Namespace.d >>Debug\DCorlib.build.rsp
echo System\NException.d >>Debug\DCorlib.build.rsp
echo System\NObject.d >>Debug\DCorlib.build.rsp
echo System\Nullable__G.d >>Debug\DCorlib.build.rsp
echo System\PlatformID.d >>Debug\DCorlib.build.rsp
echo System\Predicate__G.d >>Debug\DCorlib.build.rsp
echo System\Random.d >>Debug\DCorlib.build.rsp
echo System\SByte.d >>Debug\DCorlib.build.rsp
echo System\Single.d >>Debug\DCorlib.build.rsp
echo System\String.d >>Debug\DCorlib.build.rsp
echo System\SystemException.d >>Debug\DCorlib.build.rsp
echo System\Timespan.d >>Debug\DCorlib.build.rsp
echo System\Type.d >>Debug\DCorlib.build.rsp
echo System\TypeCode.d >>Debug\DCorlib.build.rsp
echo System\UInt16.d >>Debug\DCorlib.build.rsp
echo System\UInt32.d >>Debug\DCorlib.build.rsp
echo System\UInt64.d >>Debug\DCorlib.build.rsp
echo System\ValueType.d >>Debug\DCorlib.build.rsp
echo System\Version.d >>Debug\DCorlib.build.rsp
echo System\__Boxing.d >>Debug\DCorlib.build.rsp
echo System\__Constraints.d >>Debug\DCorlib.build.rsp
echo System\__NativeMethods.d >>Debug\DCorlib.build.rsp
echo System\__PInvokeSupport.d >>Debug\DCorlib.build.rsp
echo System\__PrimitiveExtensions.d >>Debug\DCorlib.build.rsp
echo System\__SystemExtensions.d >>Debug\DCorlib.build.rsp
echo System\__YieldAsyncSupport.d >>Debug\DCorlib.build.rsp
echo System\__YieldIterator__G.d >>Debug\DCorlib.build.rsp

"C:\Program Files (x86)\VisualD\pipedmd.exe" dmd -lib -g -debug -X -Xf"Debug\DCorlib.json" -deps="Debug\DCorlib.dep" -of"Debug\DCorlib.lib" -map "Debug\DCorlib.map" -L/NOMAP @Debug\DCorlib.build.rsp
if errorlevel 1 goto reportError
if not exist "Debug\DCorlib.lib" (echo "Debug\DCorlib.lib" not created! && goto reportError)

goto noError

:reportError
echo Building Debug\DCorlib.lib failed!

:noError
